//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class guest
    {
        public guest()
        {
            this.guestReservation = new HashSet<guestReservation>();
            this.payment = new HashSet<payment>();
        }
    
        public int guest_id { get; set; }
        public string guest_name { get; set; }
        public string guest_surname { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public int room_id { get; set; }
    
        public virtual room room { get; set; }
        public virtual ICollection<guestReservation> guestReservation { get; set; }
        public virtual ICollection<payment> payment { get; set; }
    }
}
