//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hotel_ManagementSystemEntities : DbContext
    {
        public hotel_ManagementSystemEntities()
            : base("name=hotel_ManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<employee> employee { get; set; }
        public DbSet<guest> guest { get; set; }
        public DbSet<guestReservation> guestReservation { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<room> room { get; set; }
    }
}
