//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.guest = new HashSet<guest>();
        }
    
        public int room_id { get; set; }
        public Nullable<int> room_No { get; set; }
        public string room_Type { get; set; }
    
        public virtual ICollection<guest> guest { get; set; }
    }
}
